---
- name: "Preflight - Fail if target host is not stable for this Role."
  fail:
    msg: "This role is not stable for the target operating system, {{ ansible_distribution }} {{ ansible_distribution_major_version }}."
  when: (ansible_distribution is not defined) or
        (ansible_distribution_version is not defined) or
        (ansible_distribution+" "+ansible_distribution_major_version not in logrotate_stable_os)

- name: "Install Prerequisites."
  package:
    name: logrotate
    state: present

- name: "Configure Logrotate."
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.conf
    backup: 'true'
    owner: root
    group: root
    mode: '0644'
    validate: logrotate -d %s

- name: "Configure Custom Logrotate Sections."
  template:
    src: "{{ item }}.j2"
    dest: "/etc/logrotate.d/{{ item }}"
    backup: 'true'
    owner: root
    group: root
    mode: '0644'
    validate: logrotate -d %s
  loop:
    - "btmp"
    - "wtmp"

- name: "Configure Logrotate for Webservers."
  template:
    src: "{{ webserver_name }}.j2"
    dest: "/etc/logrotate.d/{{ webserver_name }}"
    backup: 'true'
    owner: root
    group: root
    mode: '0644'
    validate: logrotate -d %s
  when: (webserver_name != "none") and (logrotate_manage_webserver | bool)

- name: "Configure Logrotate for MySQL."
  template:
    src: "mysql-server.j2"
    dest: "/etc/logrotate.d/mysql-server"
    backup: 'true'
    owner: root
    group: root
    mode: '0644'
    validate: logrotate -d %s
  when: logrotate_manage_mysql | bool
